FROM mediawiki:latest
COPY extensions/OpenIDConnect /var/www/html/extensions/OpenIDConnect
COPY extensions/PluggableAuth /var/www/html/extensions/PluggableAuth
COPY skins/Citizen /var/www/html/skins/Citizen
COPY skins/common /var/www/html/skins/common/